age=int(input('what is your current age?\n'))
age_left=(90-age)
days_left=(365*age_left)
weeks_left=(52*age_left)
months_left=(12*age_left)
print(f"You have {days_left} days, {weeks_left} weeks and {months_left} months left.")
